name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34 # Android 14
          target: google_apis
          arch: x86_64 # Emulates the x86 architecture (faster)
          force-avd-creation: true

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Gradle wrapper
        run: ./gradlew wrapper --gradle-version 8.13

      - name: Build and run unit tests
        run: ./gradlew build testDebugUnitTest

      - name: Run instrumented test
        run: ./gradlew connectedDebugAndroidTest